In [ ]:
x = np.array([1, 10, 5, 2, 8, 9])
sort_index = np.argsort(x)
print(sort_index)

# output
[0 3 2 4 5 1]

x[sort_index]

# output
array([ 1,  2,  5,  8,  9, 10])

# Argsort the first column
sorted_index_1stcol = arr[:, 0].argsort()

# Sort 'arr' by first column without disturbing the integrity of rows
arr[sorted_index_1stcol]

# output
 array([[1, 5, 4, 5],
        [2, 4, 5, 5],
        [2, 4, 1, 3],
        [2, 2, 4, 3],
        [3, 3, 2, 1],
        [3, 1, 4, 2],
        [3, 4, 5, 5],
        [4, 4, 4, 2]])

# Descending sort
arr[sorted_index_1stcol[::-1]]

# output
 array([[4, 4, 4, 2],
        [3, 4, 5, 5],
        [3, 1, 4, 2],
        [3, 3, 2, 1],
        [2, 2, 4, 3],
        [2, 4, 1, 3],
        [2, 4, 5, 5],
        [1, 5, 4, 5]])

# Sort by column 0, then by column 1
lexsorted_index = np.lexsort((arr[:, 1], arr[:, 0])) 
arr[lexsorted_index]

# output
 array([[1, 5, 4, 5],
        [2, 2, 4, 3],
        [2, 4, 5, 5],
        [2, 4, 1, 3],
        [3, 1, 4, 2],
        [3, 3, 2, 1],
        [3, 4, 5, 5],
        [4, 4, 4, 2]])
