In [ ]:
# Save single numpy array object as .npy file
np.save('myarray.npy', arr2d)  

# Save multile numy arrays as a .npz file
np.savez('array.npz', arr2d_f, arr2d_b)

# Load a .npy file
a = np.load('myarray.npy')
print(a)

# output
 [[0 1 2]
  [3 4 5]
  [6 7 8]]

# Load a .npz file
b = np.load('array.npz')
print(b.files)
b['arr_0']

# output
 ['arr_0', 'arr_1']

 array([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.]])